#
#      - name: Install dependencies
#        run: |
#          python3 -m pip install --upgrade pip
#          python3 -m pip install mkdocs
#          python3 -m pip install mkdocs-material
#      - name: Build site
#        run: mkdocs build
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./site
#

name: ci
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
